oldLighting=false
underwaterOverlay=false
vignette=false
sun=false
moon=false
stars=false
clouds=off
shadow.enabled=true
shadow.culling=false
shadowTerrain=true
shadowTranslucent=false
shadowEntities=false
shadowBlockEntities=false
shadowPlayer=false
